version: "3.7"
services:
  inmarketify:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: inmarketify
    volumes:
      - ./www:/var/www/html
      - ./config:/var/www/config
    restart: always
    depends_on:
      - api
      - pgsql
      #- next
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
  api:
    build:
      context: ./packages/api/
      dockerfile: Dockerfile
    container_name: api  
    restart: always
    volumes:
      - ./packages/api/:/home
    ports:
      - 8000:8000
    expose:
      - 8000
#  next:
#    build:
#      context: ./packages/next.im/
#      dockerfile: Dockerfile
#    container_name: next 
#    volumes:
#      - ./packages/next.im/:/usr/src
#    ports:
#      - 3000:3000
#    expose:
#      - 3000
  pgsql:
    container_name: pgsql
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - ./databases/postgresql:/var/lib/postgresql/data
volumes:
  inmarketify:
  pgsql:
  #next:
  api:
