version: "3.7"
services:
  nxt:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nxt
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
    expose:
      - 3000
volumes:
  next:
